language: c

cache:
  directories:
    - $HOME/.opam

addons:
  apt:
    packages:
      - libffi-dev
      - libzmq3-dev

env:
  global:
    - PATH=$PATH:$HOME/.bin
  matrix:
    - OCAML_VERSION=4.02.3 OPAM_VERSION=1.2.2
    - OCAML_VERSION=4.03.0 OPAM_VERSION=1.2.2
    - OCAML_VERSION=4.04.2 OPAM_VERSION=1.2.2
    - OCAML_VERSION=4.05.0+trunk OPAM_VERSION=1.2.2
    - OCAML_VERSION=4.06.0+trunk OPAM_VERSION=1.2.2
matrix:
  allow_failures:
    - env: OCAML_VERSION=4.05.0+trunk OPAM_VERSION=1.2.2
    - env: OCAML_VERSION=4.06.0+trunk OPAM_VERSION=1.2.2

before_script:
  - mkdir $HOME/.bin
  - curl -L -o $HOME/.bin/opam "https://github.com/ocaml/opam/releases/download/$OPAM_VERSION/opam-$OPAM_VERSION-$(uname -m)-$(uname -s)"
  - chmod 755 $HOME/.bin/opam
  - opam init -a -y --comp $OCAML_VERSION
  - opam install -y ocamlfind optcomp 'uint>=1.1.0' uuidm yojson atdgen 'ctypes>=0.3' ctypes-foreign 'lwt>=2.4' 'ocp-index>=1.0.1'

script:
  - eval $(opam config env)
  - make
